spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${connection.database_url}
    username: ${connection.database_username}
    password: ${connection.database_password}
    hikari:
      maximum-pool-size: 20