spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 12345
      maximum-pool-size: 20
      jdbc-url: jdbc:mysql://127.0.0.1:3306/ToDoDatabase